// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext{
        agp_version = '8.7.3'
        kotlin_version = '1.9.20'
        okhttp_version = '5.0.0-alpha.14'
        okio_version = '3.9.0'
    }
}
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

tasks.register('clean', Delete) {
    //delete rootProject.buildDir
    delete rootProject.layout.buildDirectory
}